language: node_js
node_js:
  - "7"
cache:
  directories:
    - "web/node_modules"
    - "web/elm-stuff"
branches:
  only:
  - frontend
script: cd web && npm install && npm run build

# deploy to github pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "/web/dist"
  github_token: $GITHUB_TOKEN
  on:
    branch: frontend
