language: node_js
node_js:
  - "7"

cache:
  directories:
    - web/node_modules
    - web/elm-stuff/build-artifacts
    - sysconfcpus

branches:
  only:
  - frontend

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - node --version
  - npm --version
  - cd web
  - npm install
  - mv node_modules/.bin/elm-make node_modules/.bin/elm-make-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > node_modules/.bin/elm-make
  - chmod +x node_modules/.bin/elm-make
  - elm package install --yes

script:
  - cd web
  - npm run build

# deploy to github pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "/web/dist"
  github_token: $GITHUB_TOKEN
  on:
    branch: frontend
